nuxt/modules

modules/vue-warehouse.yml
Update the repo url and maintainer
=> Fix info of `vue-warehouse`

modules/color-mode.yml, modules/composition-api.yml, modules/firebase.yml, modules/prismic.yml
`color-mode`: https://github.com/nuxt-community/color-mode-module → https://color-mode.nuxtjs.org
`composition-api`: https://github.com/nuxt-community/composition-api → https://composition-api.nuxtjs.org
`firebase`: https://github.com/nuxt-community/firebase-module → https://firebase.nuxtjs.org
`prismic`: https://github.com/nuxt-community/prismic-module → https://prismic.nuxtjs.org
=> chore(modules): update nuxtjs.org links

modules/nuxt-floating-prompt-module.yml
=> chore(modules): add nuxt floating prompt module

modules/yandex-metrika.yml
Update yandex-metrika module from `nuxt-community`
=> feat(modules): update yandex metrika module url

modules/component-cache.yml
Uniformize the extraction of `component-cache` module
=> docs: update component-cache module url

modules/chiffre.yml
=> add nuxt-chiffre

modules/animejs.yml
=> chore(module): add nuxt-animejs module

modules/nuxt-viewport.yml, static/icons/nuxt-viewport.svg
=> chore(module): add nuxt-viewport

modules/prune-html.yml
=> updated mantainer data

modules/canvas-sketch.yml
=> fix: update maintainer info for canvas-sketch

modules/humans-txt, modules/humans-txt.yml
added humans txt project module
=> chore(module): add humans-txt

website/components/CardModule.vue, website/pages/index.vue
=> design: improve card-module design

types/index.ts, website/components/filter/FilterButtons.vue, website/composables/constants.ts, website/server/api/modules.ts
=> feat: sort by last updated

package.json, website/components/TheDrawer.vue, website/components/TheMain.vue, website/components/TheSearch.vue, website/components/filter/FilterButtons.vue, website/package.json, website/windi.config.ts, yarn.lock
=> feat: drawer

modules/nuxt-hue.yml, website/static/icons/nuxt-hue.svg
A great addition to the Nuxt module ecosystem™
[![Caramelldansen_Cat_Extended](https://user-images.githubusercontent.com/25330882/143020711-286e3541-0526-4deb-965a-69cdf59f8290.gif)](https://www.youtube.com/watch?v=7K7kx1HDp-Y)
Let me know if anything ☺
=> feat: add nuxt-hue

modules/nuxt-pino-log.yml
Hello, 
We have created pino logger module for nuxt. This PR adds [nuxt-pino-log](https://github.com/kpn/nuxt-pino-log) to the list of modules
=> feat: add nuxt-pino-log to nuxt/modules

modules/directus.yml, modules/strapi.yml
Strapi Module is bridge compatible: 
https://github.com/nuxt-community/strapi-module/blob/dev/src/module.ts#L45
=> fix: strapi module compatibilty

website/components/TheMain.vue
This PR replaces the `Beta` flag for Nuxt 3 to `RC`
=> chore: display RC for Nuxt 3

modules/icons.yml, website/public/icons/icons.svg
https://github.com/gitFoxCode/nuxt-icons I made some adjustments with the help of Diizzayy
=> add nuxt-icons

modules/delay-hydration.yml, website/public/icons/lighthouse.svg
Repo: https://github.com/harlan-zw/nuxt-delay-hydration
=> feat: add delay-hydration

modules/xstate.yml
=> add xstate

modules/prismic.yml
Updated repo to the new Nuxt Modules GitHub org.
Also updated maintainers, I'm the only one actively working on it now.
Thanks 💚
=> update repo and maintainers for prismic module

modules/purgecss.yml
Has Nuxt3 support now 🙌  https://github.com/Developmint/nuxt-purgecss/commit/2fe2311920d1de6d0a445cad7645d86b7d217d30
=> chore: update purgecss

modules/session.yml
Caused by https://github.com/nuxt/modules/pull/464
=> ci: lint YAML to fix pipeline

website/components/TheNav.vue
=> fix: debounce search

lib/types.ts, website/components/CardModule.vue, website/composables/fetch.ts, website/server/api/modules.ts
Use [unjs/ungh](https://github.com/unjs/ungh) api to fetch stars and contributors
=> refactor(website): use ungh api

modules/chatwoot.yml
=> fix: update chatwoot urls

modules/pinia.yml
I updated the repo and domain links
=> chore: update pinia links

modules/appwrite.yml
=> fix: appwrite

modules/module-feed.yml
=> Add nuxt-module-feed

modules/varlet.yml
I'm sorry I made a low-level mistake.
=> fix: correct typo

modules/vee-validate.yml
Hello,
This adds the vee-validate module to the listing. This is the official plugin for Nuxt.js and Vue 3.x
=> feat: add `vee-validate` official module

icons/vexip-ui.svg, modules/unhead.yml, modules/vexip-ui.yml
=> feat: add `vexip-ui` module

modules/inkline.yml
Hey! I've updated the module setup for Inkline. Thank you!
=> feat: update inkline.yml for Inkline 4 release

modules/twemoji.yml
=> fix: correct twemoji icon extension

modules/vercel-analytics.yml
resolves #617
Don't have an icon yet, but will come up with something later
=> feat: add nuxt-vercel-analytics

modules/nuxt-vuetify.yml
=> docs: Update nuxt-vuetify.yml

modules/nuxt-feedme.yml
=> feat: add `nuxt-feedme` module (#732)

modules/device.yml, modules/logrocket.yml, modules/storybook.yml, modules/svg-sprite.yml
Moved a few modules into the `nuxt-module` org, updating their paths.
=> chore: update nuxt-module migration repos

modules/disqus.yml
To make module more easier to be discovered, more accurate description is added.
=> chore: improve description of disqus module

lib/types.ts, modules/directus.yml, modules/graphql-server.yml, modules/icon.yml, modules/link-checker.yml, modules/meilisearch.yml, modules/nuxt-gtm.yml, modules/nuxt-mongoose.yml, modules/og-image.yml, modules/quasar.yml, modules/storyblok.yml, modules/storybook.yml, modules/strapi.yml, modules/tailwindcss.yml, modules/unocss.yml, modules/vitest.yml, modules/vue-email.yml, modules/vue-macros.yml, modules/vueuse.yml
Later we could update nuxt.com to have a UI for it.
=> feat: add devtools field

modules/storybook.yml
Storybook Module is completely overwrites the old, so i have updated relevant info
=> chore: update new storybook module info

modules/storybook.yml
for some reason storybook module not showing anymore i guess the filter on compatibillity
=> fix: update version for storybook module

icons/radix-vue.svg, modules/radix-vue.yml
Radix Vue provides Nuxt Modules [out-of-the-box](https://www.radix-vue.com/overview/installation.html#nuxt-modules). Thus the PR 😁
=> feat: add `radix-vue`

modules/nuxt-payload-analyzer.yml
Not sure for the category. Please, take a look.
=> feat: add nuxt-payload-analyzer

package.json
same as all other nuxt repos (ex: https://github.com/nuxt/content/pull/2413)
=> chore: add repository and homepage to `package.json`

modules/nuxt-interpolation.yml, modules/nuxt3-interpolation.yml
=> feat: Add nuxt interpolation

modules/windicss.yml
=> fix: update windicss links to repo

modules/drupal-ce.yml
Changes:
* Reflect that the module provides a version for 3.x
* Update in maintainers
* Update to add new documentation website
=> chore: update drupal-ce metadata

modules/vue-email.yml
we moved the repo to an organization
=> chore: updated `vue-email`

modules/nuxt-svgo-loader.yml
=> feat: add `nuxt-svgo-loader`

modules/nuxt-oidc-auth.yml
=> feat: add `nuxt-oidc-auth`

modules/nuxt-auth-sanctum.yml
Updated links for the documentation and adjusted compatibility version of Nuxt
=> fix: updated nuxt-auth-sanctum meta

modules/test-utils.yml
closed #895 .
add `@nuxt/test-utils`.
- Repository: https://github.com/nuxt/test-utils
- Docs: https://nuxt.com/docs/getting-started/testing
=> feat: add `@nuxt/test-utils` (#896)

icons/pergel.svg, modules/pergel.yml
Hi Team, 
Pergel is a tailor-made solution for Nuxt and Nitro, providing swift project kickstarts and seamless integration of various modules.
=> feat: pergel

icons/pdf-frame.svg, modules/nuxt-pdf-frame.yml
=> feat: add nuxt-pdf-frame module

modules/nuxt3-leaflet.yml
Hey !
I worked on a proper documentation for `nuxt3-leaflet`, I think this is where the link should be updated ?
=> Update nuxt3-leaflet.yml : add proper documentation

modules/scripts.yml
related #953 .
I fixed `Nuxt Scripts` website link to https://scripts.nuxt.com/ .
=> fix: fix link for `Nuxt Scripts`

modules/shadcn-nuxt.yml, modules/shadcn.yml
closed #957  .
add `shadcn-nuxt`.
- Repository: https://github.com/radix-vue/shadcn-vue/tree/dev/packages/module
- Docs: https://www.shadcn-vue.com/docs/installation/nuxt
=> feat: add `shadcn-nuxt`

modules/vuetify-nuxt-module.yml
NA
`vuetify-nuxt-module` has been moved to https://github.com/vuetifyjs/nuxt-module and the docs url also changed https://nuxt.vuetifyjs.com/ (moved from Netlify to Vercel)
=> chore: update `vuetify-nuxt-module` entries

modules/nuxt-auth-sanctum.yml, modules/nuxt-laravel-echo.yml
Resolves #1044 by adding new metadata for the new module.
In this PR I added the metadata for the new package `nuxt-laravel-echo` and adjusted the compatibility property for another package of mine - `nuxt-auth-sanctum`.
=> New module added `nuxt-laravel-echo`

README.md
Navigating links for Icon module.
=> docs(README): icons path links

icons/tdesign.svg, modules/tdesign-vue-next.yml
resolves #905
https://tdesign.tencent.com/vue-next/getting-started#nuxt-3-%E4%B8%AD%E4%BD%BF%E7%94%A8
=> feat: add tdesign nuxt

icons/nuxt-query.svg, modules/nuxt-query.yml
resolves #1184
Adds @peterbud/nuxt-query to modules list
=> feat: add @peterbud/nuxt-query

modules/nuxt-auth-sanctum.yml, modules/nuxt-laravel-echo.yml, modules/nuxt-sanctum-precognition.yml
Closes #1189 and introduces a new module listing - `nuxt-sanctum-precognition`.
Added a new module entry and updated the description of already existing modules authored by me as well.
=> [Module Listing]: nuxt-sanctum-precognition

modules/nuxt-ssr-api-logger.yml
resolves https://github.com/buglavecz/nuxt-ssr-api-logger/issues/1
The nuxt cli show warning, because this yaml semver version strictly allowing only the 3.16.x nuxt versions. I change this, beacuse the module is compatible with nuxt v4 version.
=> feat(nuxt-ssr-api-logger): update compatibility version to >=4.0.0

modules/vue-gsap-flip.yml
resolves #1255 
- [ X] 🐞 Bug fix (a non-breaking change that fixes an issue)
Add the [@vue-gsap-flip/nuxt](https://github.com/lavolpecheprogramma/vue-gsap-flip/tree/master/packages/nuxt) module.
ps. Thank you for your hard work in the ecosystem!
=> feat: add vue-gsap-flip module
