nuxt/modules

- pages/index.vue
adds a link to footer for those who want to go direct to our modules docs so they can create their own Nuxt module or learn how modules work
> feat: add link to modules docs

- pages/index.vue
You can filter by query and by category. Sometimes it is not clear when you filter by query and then start clicking the categories that the query is still being filtered. This shows you what is being filtered so you can choose to clear the filter and continue only by category for example
> feat: see what you are filtering by

- nuxt.config.ts
`url-loader` returns a DataURL if the file is smaller than a byte limit, because of this behavior svg icons of `maintainer` and `start` are loads as data url. These icons are used inside the loop therefore loading them as data-url will increase page sige.
This PR change byte limit to zero and disables dataURL feature of `url-loader`
> fix(icons): prevent `url-loader` from loading small files as data url

- modules/markdownit.yml
In case of extraction of markdownit module, we need to access directly into the `nuxt-community` module.
*Requirement before to be merge :*
> feat(modules): update mardownit module url

- modules/yandex-metrika.yml
I saw a strange description about `yandex-metrika` during extraction.
I also took the opportunity to put the correct url of the repository (this is something that could have been added to the previous MR)
> fix(modules): yandex metrika module description

- components/CardModule.vue
- package.json
- yarn.lock
Deployment: https://modules-git-dev.nuxt-js.vercel.app/
> feat: update to nuxt-edge@2.15 and image@0.2.0-alpha

- modules/windicss.yml
I have tested windicss module with latest verison of Nuxt 3 and Nuxt Bridge. It's working fine.
Even the module's readme.md has info on how to implement in Nuxt 3.
> fix: updated compatibility status for windicss.yml

- website/components/CardModule.vue
- website/components/TheHeader.vue
- website/components/TheSearch.vue
- website/components/TheStats.vue
- website/pages/index.vue
- Ensure color contrasts matching AAA (using [this extension](https://chrome.google.com/webstore/detail/wcag-color-contrast-check/plnahcmalebffmaghcpcmpaciebdhgdf))
- Allow clicking on modules in nav "Modules"
- Fix sort drop down background
- Make "[logo] Modules" in nav clickable
- Replace .... with 
---
Todo 1:
- Color mode sets "system" as a preference. This makes issues when system theme is actually dark. We need to click twice to switch to light theme. 
- Color mode seems not restoring cookie state for server side-rendering
Todo 2:
I couldn't figure out for this situation that when a category is selected and clicked again, goes into a bad situation
> fix(website): fix a11y issues

- website/components/TheFooter.vue
- website/pages/index.vue
Hi!
This sets a default padding to Footer.
This solves problems with the "X module(s) found" => min-height, centering on tablets and text ("0 modules found" => "0 module found").
Previous PR #227 may be broken.
> design: responsive found modules & footer

- .eslintrc
- package.json
- yarn.lock
Adds missing eslint config : plugin:nuxt/recommended
I ran --fix, everything seems ok.
> chore: updating eslint configuration

- website/pages/index.vue
As `components: true` is set in the nuxt.config.ts, these imports have no use.
> chore: remove unuseful components imports

- website/components/TheSearch.vue
- website/pages/index.vue
The keyboard shortcut "/" is broken 'cause of a missing ref.
> fix: search a module shortcut is broken

- website/pages/index.vue
This code is not used anymore (no v-focus in app).
At the begining, an autofocus was set on all devices when page started (cf: ae84ec82e04edc832a901173aba86aa1613d16b6)
Now, autofocus is set only on desktop (PR#84 ):
```
if (!isMobile()) {
this.focusSearchInput()
}
```
> chore: removing unused directive

- website/components/TheSearch.vue
Suggestion: there should always be a minimum px-4, it's much more beautiful.
> fix: setting a minimum padding for the header

- lib/types.ts
- website/components/CardModule.vue
- website/components/TheMain.vue
- website/components/TheStats.vue
- website/composables/fetch.ts
- website/server/api/modules.ts
Closes #253
Show top 5 github contributors of each module instead of manual maintainers array (to be removed from DB)
I've also made few refactors for `stats` object in website
Currently, api.nuxtjs.org only returns `login` without name (seems limitation of gh rest API). But name fallback is added in place to reflect when we fix API issue.
Preview: https://modules-k6y576be3-nuxt-js.vercel.app/
> feat(website): use contributors counting

- modules/storybook.yml
As of v4.2.0 Storybook supports Bridge
> chore: update storybook bridge support

- lib/modules.ts
On Windows, the readModules function did not return anything. `names` was always empty. The reason is that globby does not seem to work when the pattern contains double blackslashes.
See : https://github.com/sindresorhus/globby/issues/179
> fix: replaces backslashes by slashes for globby pattern in readModules

- website/components/TheFooter.vue
This PR replaces `space-x-2` with `gap-2` , since it's [a supported property in flexbox](https://caniuse.com/?search=gap), and fixes the spacing between the Nuxt and Vercel badges.
Before:
After:
> fix(footer): spacing between logos

- modules/formkit.yml
Noticed that the FormKit yml file was missing the `npm` key so there were no download stats showing and the link was broken. This PR fixes that. Thanks!
> Adds missing npm key to formkit.yml

- modules/typed-router.yml
[`nuxt-typed-router`](https://github.com/victorgarciaesgi/nuxt-typed-router) supports Nuxt 3 and Nuxt 2. Resolves #292.
> chore: update nuxt-typed-router compatibility

- modules/robots.yml
`@nuxtjs/robots` supports Nuxt 3 and Nuxt Bridge.
ref: https://github.com/nuxt-community/robots-module/pull/52
> fix: update robots module

- README.md
Close #439 
The modified README can be found here.
https://github.com/odanado/modules/tree/fix-readme
> chore: fix table of readme

- website/components/CardModule.vue
> fix: skip image proxy for svg icons

- modules/nuxt-graphql-playground.yml
Add [`nuxt-graphql-playground`](https://github.com/pinpon-dev/nuxt-graphql-playground): A Nuxt.js module that injects a server route to serve [the GraphQL Playground](https://github.com/graphql/graphql-playground)
> Add nuxt-graphql-playground

- modules/nuxt-plausible.yml
Since `@nuxtjs/plausible` is now an official community module, I update the corresponding links.
Thanks again for the opportunity! 🌻
> chore: update `@nuxtjs/plausible` repo

- modules/component-cache.yml
learn_more link is outdated
- https://github.com/nuxt-community/component-cache-module/pull/5
> doc: update component-cache's learn_more link

- modules/vue-email.yml
@danielroe sorry to bother you, but it seems that the name was updated when the previous PR was merged, as its says root now in the website, i types the name correctly when i pushed, but somehow it got changed
> fix: correct vue-email repo subpath

- modules/vue-query.yml
This should correctly reference the package.json and display the missing informations on the website.
> fix: vue-query is a monorepo

- modules/nuxt-vue3-google-signin.yml
We have moved the repo to a new organization called WaveZync. We will use a new documentation website representing the new organization
- Adds the latest URL for vue3-google-signin documentation website
> fix: use new documentation website url

- lib/types.ts
- modules/image.yml
(context: followup for https://github.com/nuxt/cli/pull/197)
Some Nuxt modules use different major versions for Nuxt compatibility. 
This PR adds a new standard `compatibility.versionMap` (better names welcome) to support mapping compatible Nuxt version to their Corresponding Module compatible version/tag.
> feat: support compatibility version map (for image)

- renovate.json
The usage of [nuxt/renovate-config-nuxt](https://github.com/nuxt/renovate-config-nuxt) has been updated. Therefore, it has been fixed in this PR.
- ref: [fixed commit](https://github.com/nuxt/renovate-config-nuxt/commit/863fb61254efa17e435e4a58557a5243a4ee4655)
```suggestion
{
"$schema": "https://docs.renovatebot.com/renovate-schema.json",
"extends": [
-   "@nuxtjs"
+   "github>nuxt/renovate-config-nuxt",
]
}
```
The WARN that is occurring in #173 will be resolved with this fix. related nuxt/renovate-config-nuxt#58 .
```
WARN: Using npm packages for Renovate presets is now deprecated. Please migrate to repository-based presets instead.
```
> chore: fix Nuxt extends in renovate config. (#887)

- modules/vcalendar.yml
Hello team nuxt,
Apparently the old vcalendar link is not available, I think it had an update, I took the trouble to modify it... Thanks for reading.
**before**: 
https://github.com/samk-dev/vcalendar
**after**: 
https://github.com/samk-dev/nuxt-vcalendar
> fix: update link nuxt-vcalendar

- modules/plausible.yml
Just a little edito to place "Plausible Analytics" in the `Analytics` category, instead of the current `Devtools`
> fix: use `Analytics` category for Plausible module

- .github/workflows/autofix.yml
closed #690   .
The following warning was observed when running CI. It seems that the hash of autofix-ci is old.
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: autofix-ci/action@8bc06253bec489732e5f9c52884c7cace15c0160. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
#690 is a related PR, but this is an old Renovate PR.
I checked Nuxt organization, Nuxt Modules organization, but all other autofix-ci were the latest commit hash.
Therefore, this repo is the only one that has a warning.
- https://github.com/search?q=org%3Anuxt%20autofix-ci%2Faction%40&type=code
- https://github.com/search?q=org%3Anuxt-modules%20autofix-ci%2Faction%40&type=code
> chore(ci): update deps in autofix-ci

- modules/storefront-ui.yml
Alokai Storefront UI module allows to use `@storefront-ui/vue` and all its goodies like `components`, `composables` `tailwind-config` preset OOTB without any setup 
More information here https://docs.storefrontui.io/v2/getting-started/vue#nuxt-3
> feat: add alokai `@storefront-ui/nuxt` module

- modules/storybook.yml
https://github.com/nuxt/modules/pull/987 accidentally changed the info for the storybook module (via the auto-fix mechanism). This lead to a wrong npm module, see https://github.com/nuxt-modules/storybook/issues/657.
Fixes https://github.com/nuxt-modules/storybook/issues/657.
--- 
Any idea why the readme is not found at https://nuxt.com/modules/storybook?
> fix: update storybook info

- modules/element-plus.yml
resolves #1051 
Link to the Github repository actually redirects to Element Plus repo: https://github.com/element-plus/element-plus instead of Nuxt Element Plus repo: https://github.com/element-plus/nuxt-element-plus
> chore: fix repository URL for element-plus module

- modules/nuxt-prisma-devtools
Resolves #1134 
This module is an integration of [nuxt-prisma-devtools](https://github.com/gsxdsm/nuxt-prisma-devtools). nuxt-prisma-devtools integrates Prisma Studio into Nuxt DevTools, without having to use nuxt-prisma. This is useful if you'd rather not use the full nuxt-prisma integration and rather integrate manually, but want a DevTools integration.
> feat: add `nuxt-prisma-devtools`
